version: '3.1'

services:

  db:
    image: postgres:12.5
    #restart: always
    environment:
      POSTGRES_PASSWORD: phpmypostgres
    ports:
        - 5432:5432
    volumes: 
      - db_test:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
        - 6379:6379
  server:
    build: .
    ports: 
        - 80:3000
volumes: 
  db_test: