version: '3.1'

services:

  db:
    image: postgres:12.5
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
        - 5432:5432
  redis:
    image: redis
    restart: always
    ports:
        - 6379:6379
